# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:      
      match:
        macaddress: d8:c4:97:4e:45:a8
      dhcp4: no

  bridges:
    lxdbr0:
      interfaces: [enp1s0]
      addresses: [192.168.99.1/24]
      nameservers: 
       addresses: [127.0.0.1]
